* Abstract
** TEXT
A relatively unexplored geometric property of Potts models clusters is their ``diameter'', $D$ -- the longest shortest path between any two points on the cluster. We report numerical results for the fractal dimension of the diameter, $D_{min}$ and the fractal dimension of the chemical distance, $d_{min}$, for 2D critical Potts clusters with $q=1,2,3,4,5$. We find that $D_{min} = d_{min}$ within numerical error.
* Background
** Motivation
*** Determines efficiency of cluster algorithms
*** Unexplored geometric property of random clusters
*** Places bounds on communication of processes in a network
*** Comparison to previous studies of the chemical distance
*** TEXT
The Potts Model, initially introduced as a generalization of the 2-state Ising Model to $q$ possible spin states, can in fact be mapped onto the Random Cluster Model for all $q \ge 0$: $q \to 1$ corresponds to the Percolation Model, and $q \to 2$ corresponds to the Ising Model.  The Potts Model has found application in an impressively diverse range of contexts, including conformal field theory, percolation theory, knot theory, quantum groups, mathematical biology, and complex networks. Although easy to formulate, the Potts model exhibits rich phase behavior, and its study has yielded many significant insights into critical phenomena in statistical physics.

An important geometric property of Potts clusters is the ``chemical distance'', $l$ -- the length of the ``chemical'' or shortest path between two randomly chosen sites on a cluster.  The average chemical distance on critical Potts clusters is khown to scale as $\langle l \rangle \propto r^{d_{min}}$ at criticality, where $r$ is the Euclidean distance between the endpoints of the chemical path $l$. Attempts to establish a relationship between $d_{min}$ and other known critical exponents have as yet proved inconclusive.  For the $q \to 1$ (Percolation) case, much work has already been done to determine $d_{min}$ numerically \cite{Gr83, HrSt88} and an exact solution has been found using results from conformal field theory \cite{Zi99}.

In this paper we generalize previous studies of $d_{min}$ for the 2D, $q=1$ Potts Model by reporting results for the $q = 2, 3, 4$ and $5$.  We also study the critical scaling of a related quantity: the diameter, $D$, defined as the longest shortest path between any two points on a cluster.
%(An illustration of both $D$ and $l$ on a Potts cluster is shown in Figure [A]).
We show that $D$ also exhibits scaling behavior at criticality: $\langle D \rangle \propto r^{D_{min}}$; and that $d_{min} = D_{min}$ to within the error in our numerical results. 
** Potts Model
*** The Model (refer to Sokal)
*** Connection to Random Cluster Model
*** TEXT
The $q$-state Potts model consists of a lattice of Potts spin variables $\sigma_i$, each of which can have integer values $\sigma_i = 1 \dots q$.  Any two neighboring spins $\sigma_i$ and $\sigma_j$ contribute an amount $-K$ to the Hamiltonian if they have the same value, or zero otherwise; the Hamiltonian can thus be written as:
\begin{equation}
\mathcal{H} = -K \sum_{\lb i,j \rb} \delta_{\sigma_i, \sigma_j},
\end{equation}    
with $K$ a dimensionless coupling constant.

** The chemical distance and the diameter
*** Definitions
*** FIGURE illustrating typical configuration
*** Mean field expectations
**** Upper critical dimensions for perc, Ising, three-state (with refs)
**** Work of Nachmias and Peres
*** TODO d_min = 1.0 for q>5
** Swedsen Wang Algorithm
*** See Sokal's description
*** TEXT
The SW algorithm, which is itself based on the work of Fortuin and Kasteleyn \cite{FoKa}, works by first introducing bonds between neighboring spins, with probability 

\begin{equation}
p(\sigma_i,\sigma_j) = \delta_{\sigma_i, \sigma_j} (1-e^{-K}),
\end{equation}  
thus creating clusters of bonded spins.   All clusters thus formed are then, with probability 1/2, flipped by choosing a random spin value from the $q$ possible values, and assigning this value to all sites in the cluster.  Such cluster-flipping algorithms dramatically reduce critical slowing down in computer simulations of spin models, as compared with algorithms that flip each spin individually \cite{NeBa99} (e.g. the Metropolis algorithm \cite{Met}).
** Measuring the Chemical Distance
*** Methods in the literature
**** Bus bar method
**** average over various clusters
**** Grassberger growth method
*** Our methods
**** Average over various clusters and euclidean distances
**** "Random perimeter point" method
**** Expectation that they will be the same
**** TEXT
The average chemical distance $\langle l \rangle$ for each lattice size $L$ was determined in the following manner. The largest cluster in the lattice was identified, and a randomly chosen site $A$ on this cluster was used as the initial seed for a Leath growth (CITE) process, which amounts to a breadth-first growth along cluster bonds.   Each iteration $i$ of the Leath growth process covers all sites at chemical shell $i$;  once the Leath process has covered all $N$ sites in the cluster, the chemical distance $l$ between the seed site, $A$, and any other site, $B$, is thus equal to the chemical shell on which site $B$ resides.  We chose $B$ at random from the sites on the largest possible chemical shell reached from site $A$ on the cluster.  The chemical distance between $A$ and $B$ chosen in this manner was then averaged over the largest cluster in all of the lattice realizations considered. 
** Measuring the Diameter
*** Our method
** Simulation Details
*** Range of L, 16 to 128
*** Initial configuration random; discard first 10^5 iterations
*** Compare discard interval with autocorrelation time
*** Total run length for all systesm
*** Each data set consists of several runs combined
*** CPU time required in units of L^2 microseconds / iteration, type of processer
*** TODO run the system for shorter times at higher dimensions
** Data Analysis
*** Fit to power-law Ansatz D=AL^p using the standard weighted least-squares method
*** Fit points with lower cutoff of L >= L_{min} to minimize corrections to scaling
*** Choose fit with smallest L_{min} for which goodness of fit is reasonable (Q value within a certain range)
*** Error analysis
**** Data is taken at intervals assumed to be statistically independent
***** sigma = [fill in]
**** blocking method is used for comparison
***** brief blocking method description, references
* Results
** Results for D=2, q=1,2,3,4,5
*** Table
*** [FIGURE]: difference, fit and data for various q
** Table of results for D=3, q=1,2,3,4,5
** Preliminary results for D=6,4,8 for q=1,2,3 respectively
*** comparison with mean field expectations
*** TEXT
\begin{table}[h]
\begin{center}
\begin{tabular}{| l | l | l | l | l | l | l |}
\hline
$q$ & 1 & 2 & 3 & 4 & 5\\
\hline
$d_{min}$ & 1.127(3) & 1.0911(2) & 1.063(1) & 1.023(7) & (1.000) \\
%%$quality:$ &  & 0.99 & 0.96 & \\
\hline
$D_{min}$ & 1.129(2) & 1.087(8) & 1.060(2) & 1.025(2)& (1.000) \\

\hline
\end{tabular}
\caption{\label{tab:dminD2d} {\bf Results for 2D Potts Model.} Scaling exponent for the chemical distance ($d_{min}$) and for the diameter ($D_{min}$) for the 2D Potts model with various values of $q$, with system size L=4, 8, 16, 32, 48, 64, 96, 128.}
\end{center}
\end{table}
