#+LaTeX_CLASS: draft
#+OPTIONS: toc:nil author:nil t:nil
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{epsfig}
#+LATEX_HEADER: \usepackage{amssymb,amsmath}
#+LATEX_HEADER: \usepackage{bm}
#+LATEX_HEADER: \usepackage{pdfsync}
#+LATEX_HEADER:
#+LATEX_HEADER:
#+LATEX_HEADER: \usepackage{pdfsync}
#+TITLE: Draft of diameter paper
#+BEGIN_LaTeX:
\title{Diameter of Random Clusters}
\author{Don Blair}
\author{Jon Machta}
\affiliation{Department of Physics, University of Massachusetts, Amherst, MA 01003-3720}
\begin {abstract}
We define a new qeometric quantity, the diameter, on Potts Model clusters, and determine the scaling of the diameter with system size for $q=1,2,3,4$ in 2D, and $q=2$ in 4D, using a particularly efficient algorithm for $q=1$.  We find that that scaling exponents for the diameter and the chemical distance are the same within error.
\end{abstract}
\maketitle{}
#+END_LaTeX
* Motivation / Intro
  The Potts model -- a generalization of the Ising Model to $q$ spin states -- has seen many applications in a diverse array of fields: conformal field theory, percolation theory, knot theory, mathematical biology, and complex networks are some examples.  The Potts model can be mapped onto the Random Cluster Model for all $q \ge 0$, with  $q \to 1$ corresponding to the Percolation Model, and $q \to 2$ corresponding to the Ising Model.  In many of these applications, geometric properties of clusters in the system are of great interest:  e.g., the average shortest path between nodes in a complex network, the average size of the largest domain in a magnet.  Here, we are interested in the scaling of a new quantity, the *diameter*, which we define as the longest of all shortest paths between sites along satisfied bonds in the largest cluster at criticality.




are of great interest:  play an important role:  the average shortest path between nodes in a complex network, or

 Various geometric properties of the Potts model, such as the average size of the largest cluster at criticality, have been 


is an important task.  Here, we report on the scaling of a well-established geometric quantity, the chemical distance, or shortest path between two randomly chosen sites on the largest critical cluster, and show how this relates to the scaling of a new geometric quantity, the cluster diameter, which we define as the largest chemical distance between any two points on the cluster.We will use our results to evalute a recent conjecture [REF: Sokal's latest paper] relating this new exponent to the Coulomb gas blah blah via Kac blah blah.  We will compare our results for the chemical distance to those for the diameter.  Finally, we will evaluate some mean field predictions for the scaling of the diameter. 
* Body
** The chemical distance
*** Usefulness of the quantity
*** Previous attempts to measure it (lit review)
*** Sokal measurements
** The diameter
*** Usefulness of the quantity
*** Role in computer science, etc
*** Mean field theory
*** Expected relationship to chemical distance
*** Our new way of measuring it
** FIGURES:
*** chemical distance and diameter, defined
*** example cluster for q=1 or 2, chemical distance, diameter
*** explanation of new diameter method
** Results
*** Scaling of the chemical distance in 2D, Potts q=1,2,3,4
**** 4 FIGURES:  residuals for scaling exponent for each value of q
**** comparison with Sokal's results
*** Scaling of the chemical distance in q=2 in 4D, q=1 in 6D (necessary?)
**** Comparison with mean field theory
**** 2 FIGURES:  residuals for q=2 & q=1, here
*** Scaling of the diaemter in 2D, Potts q=1 -- high precision
**** 1 FIGURE: residuals
*** Scaling of the diameter in 2D, Potts q=1,2,3,4 -- comparison with chemical distance



















* Old Intro
** Background to the Potts Model
** Tests of the Potts Model
** This is all we need to know
** Not much more syntax highlighting
*** Big test
*** Other test
*** Finish the damn outline
Here is a test \cite{OsSo04}.  

$\lb a + b \rb$    
    
The Potts Model, initially introduced as a generalization of the 2-state Ising Model to $q$ possible spin states, can in fact be mapped onto the Random Cluster Model for all $q \ge 0$, with $q \to 1$ corresponding to the Percolation Model, and $q \to 2$ corresponding to the Ising Model.  The Potts Model has found application in an impressively diverse range of applications, including conformal field theory, percolation theory, knot theory, quantum groups, mathematical biology, and complex networks.    
%more specific ...    
Although easy to formulate, the model exhibits rich phase behavior, and its study has yielded many significant insights into critical phenomena in statistical physics. 

An important *geometric* property of Potts clusters that has proved very useful in describing transport and diffusion processes in random media is the ``chemical distance'', $l$ -- the length of the ``chemical'' or shortest path between two randomly chosen sites on a cluster.  The average chemical distance on critical Potts clusters has been shown to scale as $\bar{l} \propto r^{d_{min}}$ at criticality, where $r$ is the Euclidean distance between the endpoints of the chemical path $l$. Attempts to establish a relationship between $d_{min}$ and other known critical exponents have, as yet, proved inconclusive [refs].  For the $q \to 1$ (Percolation) case, much work has already been done to determine $d_{min}$ numerically \cite{Gr83, HrSt88} and an exact solution has been found using results from conformal field theory \cite{Zi99}.
 
In this paper we generalize previous studies of $d_{min}$ for the 2D, $q=1$ Potts Model by reporting results for the $q = 2, 3$ and $4$ for both Potts Models in both 2D and 3D.  We also study the critical scaling of a related quantity: the diameter, $D$, defined as the longest of all the shortest paths between points on a cluster. (An illustration of both $D$ and $l$ on a Potts cluster is shown in Figure [A]).  We show that $D$ also exhibits scaling behavior at criticality: $\bar{D} \propto r^{D_{min}}$; and that, significantly, $d_{min} = D_{min}$ to within the error of our numerical results.  
 
We also propose a possible relationship between both $D_{min}, d_{min}$ and the dynamical exponent, $z$.

 | Name  | Phone | Age |
 |-------+-------+-----|
 | Peter |  1234 |  17 |
 | Anna  |  4321 |  25 |

* Methods
** type 1
** type 2
*** sub-sub
\begin{figure}[htp]
\centering
\includegraphics[width=.85\textwidth]{boot}
\caption{$d_{min}$ for D=2, q=1.}\label{fig:1}
\end{figure}


* Bibliography

\bibliographystyle{plain}
\bibliography{/home/dwblair/Dropbox/dwbdocs/physics/writing/bibfiles/dwbreferences}
